-- ═══════════════════════════════════════════════════════════════════════
-- ia_uso / calibração — o euro deixa de ser adivinhado e passa a ser MEDIDO
-- ═══════════════════════════════════════════════════════════════════════
-- Corre DEPOIS do `ia_uso.sql` (usa a `registos`, a `config` e a
-- `sou_admin()` que estão lá). É IDEMPOTENTE.
--
-- O PROBLEMA QUE ISTO RESOLVE. O `registos.custo_estimado_eur` sai de
-- constantes escritas à mão dentro de cada uma das nove Edge Functions
-- (`CUSTO_ANALISE_EUR`, `CUSTO_CALENDARIO_EUR`, `CUSTO_VERIFICACAO_EUR`…).
-- Não é um preço publicado, ninguém as vai lá atualizar quando a Google
-- mexer na tabela, e a pesquisa Google — que é faturada À PARTE, por
-- pedido — não entra em nenhuma delas. Um número assim não serve para
-- controlar custo nenhum: serve para dar ordem de grandeza, e era isso
-- que o `ia_uso.sql` já dizia de si próprio.
--
-- A IDEIA, e é o que muda tudo: DE VEZ EM QUANDO LÊ-SE O SALDO REAL DA
-- CONTA GOOGLE e grava-se aqui. Entre duas leituras há um euro OBSERVADO,
-- e nessa mesma janela a `registos` tem todas as chamadas com os tokens
-- que cada uma gastou. Os TOKENS já eram facto; o euro passa a ser facto
-- também. O que sobra de estimativa — como repartir aquele euro por
-- aquelas chamadas — é só isso, e está todo aqui à vista.
--
-- COMO SE REPARTE: a `precos` dá a FORMA, a leitura dá a ESCALA.
--   · a `precos` diz quanto vale um token de entrada comparado com um de
--     saída, e este modelo comparado com aquele. São RÁCIOS, não preços —
--     ninguém tem de os acertar com a tabela da Google;
--   · o PESO de uma chamada é a soma dos seus tokens a esses rácios, mais
--     a pesquisa Google quando a houve;
--   · o FATOR da janela é o euro observado a dividir pela soma dos pesos.
--     É ele que corrige tudo o resto de uma vez: se os rácios estiverem
--     20% curtos, o fator fica 20% maior e as contas fecham na mesma.
--
-- A INVARIANTE: a soma das chamadas de uma janela dá EXACTAMENTE o euro
-- que foi lido — por construção e não por arredondamento, porque
-- `Σ(peso × fator) = Σpeso × (real / Σpeso) = real`. É a mesma regra que
-- já segura a divisão da fatura no SplitBill e o rateio das compras no
-- FestasBV: a soma das partes tem de dar a fatura.
--   E é por isso que aqui NÃO se arredonda ao cêntimo. Uma chamada custa
--   milésimos de euro; arredondá-la punha metade a zero e a outra metade
--   a um cêntimo, e a invariante ia com elas.
--
-- O QUE ISTO NÃO CONSEGUE DIZER, e é preciso saber-se:
--   · dentro de uma janela, a repartição continua a depender dos rácios.
--     O TOTAL está certo; a chamada individual está tão certa quanto a
--     `precos` estiver. Mais leituras não melhoram isso — o que melhora é
--     mexer nos rácios e ver o `desvio` das janelas descer;
--   · as chamadas ANTERIORES à primeira leitura e as POSTERIORES à última
--     não caem em janela nenhuma. Levam o fator da janela mais próxima e
--     vêm marcadas `provisorio` — nunca se calam nem se inventam;
--   · o `tokens_pensamento` esteve a NULL até 20/09/2026 (o
--     `usageMetadata()` local de cinco das nove functions deitava fora o
--     `thoughtsTokenCount`). No histórico anterior a essa data, uma
--     chamada que gastou o orçamento a PENSAR e não escreveu nada — o
--     "200 vazio" — pesa quase nada e leva menos euros do que gastou. O
--     total da janela fica certo à mesma; é a repartição dentro dela que
--     mente, e mente sempre no mesmo sentido.
-- ═══════════════════════════════════════════════════════════════════════

-- ── As leituras do saldo ───────────────────────────────────────────────
-- Uma linha por vez que se vai ao painel da Google ver quanto lá está.
--
-- DOIS FEITIOS, porque as contas da Google não se leem todas da mesma
-- maneira: um saldo pré-pago DESCE (`tipo='saldo'`) e um gasto acumulado
-- SOBE (`tipo='gasto'`). Suportam-se os dois em vez de se adivinhar qual
-- é — adivinhar trocava o sinal, e a app dizia que não se tinha gasto
-- nada exactamente quando mais se tinha gasto.
--
-- `carregado_eur` é o que se pôs na conta DESDE a leitura anterior. Sem
-- ele, um carregamento a meio da janela lia-se como dinheiro que não se
-- gastou: o saldo subia e a janela dava negativa.
CREATE TABLE IF NOT EXISTS ia_uso.leituras (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  lido_em       timestamptz NOT NULL DEFAULT now(),
  tipo          text NOT NULL DEFAULT 'saldo' CHECK (tipo IN ('saldo', 'gasto')),
  valor_eur     numeric NOT NULL CHECK (valor_eur >= 0),
  carregado_eur numeric NOT NULL DEFAULT 0 CHECK (carregado_eur >= 0),
  nota          text,
  criado_em     timestamptz NOT NULL DEFAULT now()
);

-- Duas leituras ao mesmo instante davam uma janela de largura zero com
-- chamadas lá dentro — e um fator sem sentido.
CREATE UNIQUE INDEX IF NOT EXISTS leituras_lido_em_idx
  ON ia_uso.leituras USING btree (lido_em);

-- ── Os rácios (a FORMA, nunca o preço) ─────────────────────────────────
-- Estes números NÃO são a tabela de preços da Google e não têm de bater
-- certo com ela. Só importa a PROPORÇÃO entre eles. A escala vem toda do
-- fator da janela, e é isso que os torna seguros de errar.
--
-- `modelo = '*'` é a linha de recurso, para um modelo que apareça amanhã
-- sem ninguém o ter acrescentado aqui — é o que evita que uma chamada
-- fique com peso zero e leve euros a menos.
--
-- `eur_pensamento_1m` a NULL = cobra-se como saída, que é o que a Google
-- faz hoje. Fica como coluna própria para o dia em que deixar de ser.
--
-- `eur_pesquisa` é POR PEDIDO e não por token: o grounding com pesquisa
-- Google é faturado à parte, e era exactamente o que nenhuma das
-- constantes das Edge Functions sabia incluir.
CREATE TABLE IF NOT EXISTS ia_uso.precos (
  modelo            text PRIMARY KEY,
  eur_entrada_1m    numeric NOT NULL CHECK (eur_entrada_1m >= 0),
  eur_saida_1m      numeric NOT NULL CHECK (eur_saida_1m >= 0),
  eur_pensamento_1m numeric CHECK (eur_pensamento_1m >= 0),
  eur_pesquisa      numeric NOT NULL DEFAULT 0 CHECK (eur_pesquisa >= 0),
  nota              text
);

INSERT INTO ia_uso.precos (modelo, eur_entrada_1m, eur_saida_1m, eur_pensamento_1m, eur_pesquisa, nota) VALUES
  ('*',                        0.10, 0.40, NULL, 0.030, 'linha de recurso: um modelo que ainda não está aqui'),
  ('gemini-flash-latest',      0.30, 2.50, NULL, 0.030, 'o ponteiro do flash'),
  ('gemini-flash-lite-latest', 0.10, 0.40, NULL, 0.030, 'o ponteiro do lite')
ON CONFLICT (modelo) DO NOTHING;

-- ── O peso de uma chamada ──────────────────────────────────────────────
-- UMA SÓ DEFINIÇÃO disto, e é esta. Se um dia o peso passar a contar mais
-- alguma coisa (cache de contexto, imagens à parte), muda-se aqui e o
-- resto — janelas, custo por chamada, resumo — acompanha sozinho. Dois
-- sítios a pesar a mesma chamada davam dois euros para a mesma linha.
--
-- O `ORDER BY (modelo = '*')` é o que faz a linha exacta ganhar à de
-- recurso: num `UNION ALL` sem ordem, qual delas vinha primeiro era o
-- acaso, e o mesmo modelo pesava de duas maneiras conforme o plano.
CREATE OR REPLACE FUNCTION ia_uso.peso(r ia_uso.registos)
RETURNS numeric
LANGUAGE sql STABLE
SET search_path TO 'ia_uso', 'public'
AS $$
  SELECT (
      COALESCE(r.tokens_entrada, 0)    * p.eur_entrada_1m
    + COALESCE(r.tokens_saida, 0)      * p.eur_saida_1m
    + COALESCE(r.tokens_pensamento, 0) * COALESCE(p.eur_pensamento_1m, p.eur_saida_1m)
    ) / 1000000.0
    + CASE WHEN r.pesquisa_web THEN p.eur_pesquisa ELSE 0 END
  FROM ia_uso.precos p
  WHERE p.modelo IN (COALESCE(r.modelo, '*'), '*')
  ORDER BY (p.modelo = '*')
  LIMIT 1;
$$;

-- ── As janelas, em cru ─────────────────────────────────────────────────
-- Interna: é a peça de que tudo o resto vive. Uma linha por par de
-- leituras consecutivas, com o euro observado, o peso das chamadas que lá
-- caíram e o fator que os reconcilia.
--
-- Leituras de tipos diferentes seguidas não dão janela (`real_eur` a
-- NULL): misturar um saldo que desce com um gasto que sobe dava um número
-- sem significado, e é melhor não dizer nada do que dizer isso. Um
-- `real_eur` NEGATIVO também não dá fator — é sinal de que faltou
-- declarar um carregamento, e inventar um fator negativo era espalhar
-- custos negativos por chamadas que custaram dinheiro.
CREATE OR REPLACE FUNCTION ia_uso.fatores()
RETURNS TABLE (
  leitura_id bigint, de timestamptz, ate timestamptz, tipo text,
  real_eur numeric, chamadas bigint, peso_total numeric,
  estimado_eur numeric, fator numeric, nota text
)
LANGUAGE sql STABLE
SET search_path TO 'ia_uso', 'public'
AS $$
  WITH pares AS (
    SELECT l.id, l.tipo, l.valor_eur, l.carregado_eur, l.lido_em, l.nota,
           lag(l.lido_em)   OVER w AS de,
           lag(l.valor_eur) OVER w AS val_ant,
           lag(l.tipo)      OVER w AS tipo_ant
      FROM ia_uso.leituras l
    WINDOW w AS (ORDER BY l.lido_em)
  ), j AS (
    SELECT p.id, p.de, p.lido_em AS ate, p.tipo, p.nota,
      CASE
        WHEN p.tipo_ant IS DISTINCT FROM p.tipo THEN NULL
        WHEN p.tipo = 'saldo' THEN p.val_ant + p.carregado_eur - p.valor_eur
        WHEN p.valor_eur >= p.val_ant THEN p.valor_eur - p.val_ant
        -- gasto acumulado que DESCEU = a conta virou o mês e voltou a
        -- zero; o que lá está agora é o que se gastou desde a viragem.
        ELSE p.valor_eur
      END AS real_eur
      FROM pares p
     WHERE p.de IS NOT NULL
  )
  SELECT j.id, j.de, j.ate, j.tipo, j.real_eur,
         a.chamadas, a.peso_total, a.estimado_eur,
         CASE WHEN a.peso_total > 0 AND j.real_eur >= 0
              THEN j.real_eur / a.peso_total END,
         j.nota
    FROM j
    CROSS JOIN LATERAL (
      SELECT count(*) AS chamadas,
             COALESCE(sum(ia_uso.peso(r)), 0) AS peso_total,
             COALESCE(sum(r.custo_estimado_eur), 0) AS estimado_eur
        FROM ia_uso.registos r
       WHERE r.criado_em > j.de AND r.criado_em <= j.ate
    ) a;
$$;

-- ── O custo medido de cada chamada ─────────────────────────────────────
-- `peso × fator da janela onde caiu`. Interna e SEM LIMITE: é a base de
-- que os agregados e a lista vivem, e calcula os fatores UMA vez para
-- todas as linhas. A primeira versão perguntava o fator por linha e era
-- quadrática — com sete registos não se nota, com sete mil nota-se muito.
--
-- Fora de qualquer janela usa-se o fator mais PRÓXIMO no tempo e a linha
-- vem `provisorio`. Sem leitura nenhuma ainda não há fator: `custo_eur`
-- fica NULL e a app mostra a estimativa antiga dizendo que é isso que
-- está a mostrar. NÃO se cai para o `custo_estimado_eur` às escondidas —
-- um número medido e um número adivinhado não se somam na mesma coluna
-- sem se dizer qual é qual.
CREATE OR REPLACE FUNCTION ia_uso.calc()
RETURNS TABLE (id bigint, peso numeric, fator numeric, custo_eur numeric, provisorio boolean)
LANGUAGE sql STABLE
SET search_path TO 'ia_uso', 'public'
AS $$
  WITH f AS (
    SELECT x.de, x.ate, x.fator FROM ia_uso.fatores() x WHERE x.fator IS NOT NULL
  )
  SELECT r.id,
         ia_uso.peso(r),
         c.fator,
         ia_uso.peso(r) * c.fator,
         COALESCE(c.provisorio, true)
    FROM ia_uso.registos r
    LEFT JOIN LATERAL (
      SELECT f.fator,
             NOT (r.criado_em > f.de AND r.criado_em <= f.ate) AS provisorio
        FROM f
       ORDER BY (r.criado_em > f.de AND r.criado_em <= f.ate) DESC,
                LEAST(abs(extract(epoch FROM r.criado_em - f.ate)),
                      abs(extract(epoch FROM r.criado_em - f.de)))
       LIMIT 1
    ) c ON true;
$$;

-- ═══════════════════════════════════════════════════════════════════════
-- O que a app chama (tudo com o portão `sou_admin()` lá dentro)
-- ═══════════════════════════════════════════════════════════════════════

-- As janelas para o ecrã do saldo. O `desvio` é quanto a estimativa das
-- Edge Functions andava longe da realidade — é ele que diz se vale a pena
-- mexer nos rácios, e é a única coisa que esta app pode dizer sobre a
-- qualidade da própria conta.
CREATE OR REPLACE FUNCTION ia_uso.janelas()
RETURNS jsonb
LANGUAGE plpgsql STABLE SECURITY DEFINER
SET search_path TO 'ia_uso', 'public'
AS $$
BEGIN
  IF NOT ia_uso.sou_admin() THEN
    RAISE EXCEPTION 'Só o admin vê os acessos à IA.';
  END IF;
  RETURN COALESCE((
    SELECT jsonb_agg(
             to_jsonb(f) || jsonb_build_object(
               'desvio', CASE WHEN f.estimado_eur > 0 AND f.real_eur IS NOT NULL
                              THEN (f.real_eur - f.estimado_eur) / f.estimado_eur END)
             ORDER BY f.ate DESC)
      FROM ia_uso.fatores() f
  ), '[]'::jsonb);
END;
$$;

-- Os registos com o custo medido, do mais recente para o mais antigo.
-- Limite capado a 1000 — é um painel, não um export.
CREATE OR REPLACE FUNCTION ia_uso.custos(
  p_limite integer DEFAULT 200,
  p_app text DEFAULT NULL,
  p_desde timestamptz DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql STABLE SECURITY DEFINER
SET search_path TO 'ia_uso', 'public'
AS $$
BEGIN
  IF NOT ia_uso.sou_admin() THEN
    RAISE EXCEPTION 'Só o admin vê os acessos à IA.';
  END IF;
  RETURN COALESCE((
    SELECT jsonb_agg(
             to_jsonb(r) || jsonb_build_object(
               'peso', c.peso, 'fator', c.fator,
               'custo_eur', c.custo_eur, 'provisorio', c.provisorio)
             ORDER BY r.criado_em DESC)
      FROM (
        SELECT * FROM ia_uso.registos
         WHERE (p_app IS NULL OR app = p_app)
           AND (p_desde IS NULL OR criado_em >= p_desde)
         ORDER BY criado_em DESC
         LIMIT LEAST(GREATEST(COALESCE(p_limite, 200), 1), 1000)
      ) r
      JOIN ia_uso.calc() c ON c.id = r.id
  ), '[]'::jsonb);
END;
$$;

-- Os totais em euros MEDIDOS, com a estimativa ao lado para se ver a
-- diferença. Irmão do `ia_uso.resumo()` do `ia_uso.sql`, que só sabe
-- somar a estimativa: são duas perguntas diferentes e por isso são duas
-- funções — uma diz o que o código julgava que ia custar, esta diz o que
-- custou. O painel usa esta.
CREATE OR REPLACE FUNCTION ia_uso.resumo_medido(p_dias integer DEFAULT 30)
RETURNS jsonb
LANGUAGE plpgsql STABLE SECURITY DEFINER
SET search_path TO 'ia_uso', 'public'
AS $$
DECLARE
  v_desde timestamptz := now() - make_interval(days => GREATEST(COALESCE(p_dias, 30), 1));
BEGIN
  IF NOT ia_uso.sou_admin() THEN
    RAISE EXCEPTION 'Só o admin vê os acessos à IA.';
  END IF;

  RETURN (
    WITH m AS (
      SELECT r.*, c.custo_eur, c.provisorio
        FROM ia_uso.registos r JOIN ia_uso.calc() c ON c.id = r.id
    )
    SELECT jsonb_build_object(
      'janelaDias', p_dias,
      'calibrado', EXISTS (SELECT 1 FROM ia_uso.fatores() WHERE fator IS NOT NULL),
      'porApp', COALESCE((
        SELECT jsonb_agg(x ORDER BY (x ->> 'pedidos')::int DESC) FROM (
          SELECT jsonb_build_object(
            'app', m.app,
            'pedidos', count(*),
            'ok', count(*) FILTER (WHERE m.estado = 'ok'),
            'erro', count(*) FILTER (WHERE m.estado = 'erro'),
            'tokensEntrada', COALESCE(sum(m.tokens_entrada), 0),
            'tokensSaida', COALESCE(sum(m.tokens_saida), 0),
            'tokensPensamento', COALESCE(sum(m.tokens_pensamento), 0),
            'custoEur', sum(m.custo_eur),
            'estimadoEur', COALESCE(sum(m.custo_estimado_eur), 0),
            'provisorio', bool_or(m.provisorio),
            'ultimaChamada', max(m.criado_em)
          ) AS x FROM m GROUP BY m.app
        ) t
      ), '[]'::jsonb),
      'porModelo', COALESCE((
        SELECT jsonb_agg(x ORDER BY (x ->> 'pedidos')::int DESC) FROM (
          SELECT jsonb_build_object(
            'modelo', COALESCE(m.modelo, '(desconhecido)'),
            'pedidos', count(*),
            'tokensEntrada', COALESCE(sum(m.tokens_entrada), 0),
            'tokensSaida', COALESCE(sum(m.tokens_saida), 0),
            'tokensPensamento', COALESCE(sum(m.tokens_pensamento), 0),
            'custoEur', sum(m.custo_eur),
            'estimadoEur', COALESCE(sum(m.custo_estimado_eur), 0)
          ) AS x FROM m GROUP BY m.modelo
        ) t
      ), '[]'::jsonb),
      'janela', (
        SELECT jsonb_build_object(
          'pedidos', count(*), 'custoEur', sum(m.custo_eur),
          'estimadoEur', COALESCE(sum(m.custo_estimado_eur), 0)
        ) FROM m WHERE m.criado_em >= v_desde
      ),
      'total', (
        SELECT jsonb_build_object(
          'pedidos', count(*), 'custoEur', sum(m.custo_eur),
          'estimadoEur', COALESCE(sum(m.custo_estimado_eur), 0)
        ) FROM m
      )
    )
  );
END;
$$;

-- ── Escrever uma leitura ───────────────────────────────────────────────
CREATE OR REPLACE FUNCTION ia_uso.registar_leitura(
  p_valor_eur numeric,
  p_tipo text DEFAULT 'saldo',
  p_carregado_eur numeric DEFAULT 0,
  p_lido_em timestamptz DEFAULT NULL,
  p_nota text DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER
SET search_path TO 'ia_uso', 'public'
AS $$
DECLARE
  v_id bigint;
  v_quando timestamptz := COALESCE(p_lido_em, now());
BEGIN
  IF NOT ia_uso.sou_admin() THEN
    RAISE EXCEPTION 'Só o admin regista leituras do saldo.';
  END IF;
  IF p_valor_eur IS NULL OR p_valor_eur < 0 THEN
    RAISE EXCEPTION 'Valor inválido.';
  END IF;
  IF COALESCE(p_tipo, '') NOT IN ('saldo', 'gasto') THEN
    RAISE EXCEPTION 'Tipo tem de ser saldo ou gasto.';
  END IF;
  -- Uma leitura no futuro apanhava chamadas que ainda não aconteceram.
  IF v_quando > now() + interval '1 hour' THEN
    RAISE EXCEPTION 'Não se lê um saldo que ainda não existe.';
  END IF;

  INSERT INTO ia_uso.leituras (lido_em, tipo, valor_eur, carregado_eur, nota)
  VALUES (v_quando, p_tipo, p_valor_eur, COALESCE(p_carregado_eur, 0),
          NULLIF(trim(COALESCE(p_nota, '')), ''))
  RETURNING id INTO v_id;

  RETURN jsonb_build_object('id', v_id, 'lido_em', v_quando);
END;
$$;

CREATE OR REPLACE FUNCTION ia_uso.apagar_leitura(p_id bigint)
RETURNS text
LANGUAGE plpgsql SECURITY DEFINER
SET search_path TO 'ia_uso', 'public'
AS $$
BEGIN
  IF NOT ia_uso.sou_admin() THEN
    RAISE EXCEPTION 'Só o admin apaga leituras do saldo.';
  END IF;
  DELETE FROM ia_uso.leituras WHERE id = p_id;
  RETURN 'ok';
END;
$$;

CREATE OR REPLACE FUNCTION ia_uso.listar_leituras()
RETURNS jsonb
LANGUAGE plpgsql STABLE SECURITY DEFINER
SET search_path TO 'ia_uso', 'public'
AS $$
BEGIN
  IF NOT ia_uso.sou_admin() THEN
    RAISE EXCEPTION 'Só o admin vê as leituras do saldo.';
  END IF;
  RETURN COALESCE((
    SELECT jsonb_agg(to_jsonb(l) ORDER BY l.lido_em DESC) FROM ia_uso.leituras l
  ), '[]'::jsonb);
END;
$$;

-- ── Os rácios, a ler e a afinar ────────────────────────────────────────
CREATE OR REPLACE FUNCTION ia_uso.listar_precos()
RETURNS jsonb
LANGUAGE plpgsql STABLE SECURITY DEFINER
SET search_path TO 'ia_uso', 'public'
AS $$
BEGIN
  IF NOT ia_uso.sou_admin() THEN
    RAISE EXCEPTION 'Só o admin vê os rácios.';
  END IF;
  RETURN COALESCE((
    SELECT jsonb_agg(to_jsonb(p) ORDER BY p.modelo) FROM ia_uso.precos p
  ), '[]'::jsonb);
END;
$$;

CREATE OR REPLACE FUNCTION ia_uso.definir_preco(
  p_modelo text,
  p_entrada numeric,
  p_saida numeric,
  p_pensamento numeric DEFAULT NULL,
  p_pesquisa numeric DEFAULT 0,
  p_nota text DEFAULT NULL
)
RETURNS text
LANGUAGE plpgsql SECURITY DEFINER
SET search_path TO 'ia_uso', 'public'
AS $$
BEGIN
  IF NOT ia_uso.sou_admin() THEN
    RAISE EXCEPTION 'Só o admin mexe nos rácios.';
  END IF;
  IF COALESCE(trim(p_modelo), '') = '' THEN
    RAISE EXCEPTION 'Falta o modelo.';
  END IF;
  INSERT INTO ia_uso.precos (modelo, eur_entrada_1m, eur_saida_1m,
                             eur_pensamento_1m, eur_pesquisa, nota)
  VALUES (trim(p_modelo), COALESCE(p_entrada, 0), COALESCE(p_saida, 0),
          p_pensamento, COALESCE(p_pesquisa, 0),
          NULLIF(trim(COALESCE(p_nota, '')), ''))
  ON CONFLICT (modelo) DO UPDATE SET
    eur_entrada_1m    = EXCLUDED.eur_entrada_1m,
    eur_saida_1m      = EXCLUDED.eur_saida_1m,
    eur_pensamento_1m = EXCLUDED.eur_pensamento_1m,
    eur_pesquisa      = EXCLUDED.eur_pesquisa,
    nota              = EXCLUDED.nota;
  RETURN 'ok';
END;
$$;

-- ═══════════════════════════════════════════════════════════════════════
-- RLS, GRANTS e policies
-- ═══════════════════════════════════════════════════════════════════════
-- Mesmo desenho do `ia_uso.sql`: as funções que a app chama são SECURITY
-- DEFINER com o portão `sou_admin()` lá dentro, e as policies são o
-- segundo cinto para quem chegue às tabelas por REST. Sem os GRANTs nada
-- disto é alcançável — foi o bloco que faltou correr à primeira, em
-- 20/09/2026, e a avaria foi silenciosa.
--
-- As três INTERNAS (`peso`, `fatores`, `calc`) ficam fechadas a quem tem
-- login: não passam por `sou_admin()` nenhum, e servem-se sozinhas de
-- dentro das DEFINER, que correm como o dono. Uma função nasce com
-- EXECUTE para PUBLIC, e um REVOKE esquecido não dá erro — dá uma porta
-- aberta calada.
ALTER TABLE ia_uso.leituras ENABLE ROW LEVEL SECURITY;
ALTER TABLE ia_uso.precos   ENABLE ROW LEVEL SECURITY;

GRANT SELECT ON ia_uso.leituras, ia_uso.precos TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON ia_uso.leituras, ia_uso.precos TO service_role;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA ia_uso TO service_role;

GRANT EXECUTE ON FUNCTION
  ia_uso.janelas(), ia_uso.custos(integer, text, timestamptz),
  ia_uso.resumo_medido(integer), ia_uso.listar_leituras(),
  ia_uso.registar_leitura(numeric, text, numeric, timestamptz, text),
  ia_uso.apagar_leitura(bigint), ia_uso.listar_precos(),
  ia_uso.definir_preco(text, numeric, numeric, numeric, numeric, text)
  TO authenticated, service_role;

-- E REVOGAR, que o GRANT acima só acrescenta. Uma função nasce com
-- EXECUTE para PUBLIC, e o `ALTER DEFAULT PRIVILEGES` do `ia_uso.sql` dá
-- EXECUTE a `authenticated` em TODAS as funções novas deste schema — por
-- isso as internas nascem abertas às duas e é preciso fechá-las à mão.
-- Não vazavam (a RLS da `registos` é admin-only e as DEFINER têm o portão
-- lá dentro), mas a trava é para ser dupla, como no catálogo.
--
-- FUNÇÃO INTERNA NOVA = mais uma linha aqui. Não dá erro esquecê-la; dá
-- uma porta aberta calada, que é a pior espécie.
REVOKE ALL ON FUNCTION ia_uso.peso(ia_uso.registos) FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION ia_uso.fatores()             FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION ia_uso.calc()                FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION ia_uso.peso(ia_uso.registos), ia_uso.fatores(), ia_uso.calc()
  TO service_role;

-- As que a app chama ficam fechadas ao anon — ninguém entra aqui sem
-- login, e o schema inteiro também não tem de estar à vista dele.
REVOKE ALL ON FUNCTION
  ia_uso.janelas(), ia_uso.custos(integer, text, timestamptz),
  ia_uso.resumo_medido(integer), ia_uso.listar_leituras(),
  ia_uso.registar_leitura(numeric, text, numeric, timestamptz, text),
  ia_uso.apagar_leitura(bigint), ia_uso.listar_precos(),
  ia_uso.definir_preco(text, numeric, numeric, numeric, numeric, text)
  FROM PUBLIC, anon;
REVOKE USAGE ON SCHEMA ia_uso FROM anon;

DROP POLICY IF EXISTS leituras_admin_le ON ia_uso.leituras;
CREATE POLICY leituras_admin_le ON ia_uso.leituras
  FOR SELECT TO authenticated USING (ia_uso.sou_admin());

DROP POLICY IF EXISTS precos_admin_le ON ia_uso.precos;
CREATE POLICY precos_admin_le ON ia_uso.precos
  FOR SELECT TO authenticated USING (ia_uso.sou_admin());

-- ── Conferir depois de correr ──────────────────────────────────────────
-- select count(*) from ia_uso.precos;                                 -- 3
-- select has_function_privilege('authenticated','ia_uso.janelas()','EXECUTE');
-- select p.proname, has_function_privilege('anon', p.oid, 'EXECUTE')
--   from pg_proc p join pg_namespace n on n.oid = p.pronamespace
--  where n.nspname = 'ia_uso';                                       -- tudo false
-- select ia_uso.janelas();                                            -- [] sem leituras
-- select * from ia_uso.calc() limit 5;                                -- custo_eur a NULL
